name: Check

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup kernel for build, increase watchers
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
      - name: Use Node.js 24.10.0
        uses: actions/setup-node@v2
        with:
          node-version: 24.10.0
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.201'
      - name: Setup python
        uses: actions/setup-python@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          version: '0.8.5'
      - name: Install python dependencies
        shell: bash
        run: uv sync --locked --all-extras --dev
      - name: Install node dependencies
        run: npm ci
      - name: Compile examples
        run: npm run check
      - name: Test examples
        run: npm run test
        env:
          CRIIPTO_SIGNATURES_CLIENT_ID: ${{ secrets.CRIIPTO_SIGNATURES_CLIENT_ID }}
          CRIIPTO_SIGNATURES_CLIENT_SECRET: ${{ secrets.CRIIPTO_SIGNATURES_CLIENT_SECRET }}
