
name: Check

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup kernel for build, increase watchers
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
      - name: Use Node.js 18.19.0
        uses: actions/setup-node@v2
        with:
          node-version: 18.19.0
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.201'
      - name: Install dependencies
        run: npm ci
      - name: Check
        run: npm run check